export default {
	SET_COUNTDOWN: 'SET_COUNTDOWN',
	RESET_COUNTDOWN: 'RESET_COUNTDOWN',
	DECREMENT_COUNTDOWN: 'DECREMENT_COUNTDOWN',
	START_COUNTDOWN: 'START_COUNTDOWN',
	PAUSE_COUNTDOWN: 'PAUSE_COUNTDOWN',

	ACTIVATE_COUNTDOWN: 'ACTIVATE_COUNTDOWN',
	DEACTIVATE_COUNTDOWN: 'DEACTIVATE_COUNTDOWN'
}